---
- name: Create DaemonSet to prepull images
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'daemonset-prepull-images.yml.j2') | from_yaml }}"

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent | bool
