---
become_override: false
silent: false

ocp4_workload_gitops_devspaces_gitops_repo: https://github.com/treddy08/agnosticg
ocp4_workload_gitops_devspaces_gitops_repo_revision: main
ocp4_workload_gitops_devspaces_namespace: openshift-devspaces

# devspaces
# ocp4_workload_gitops_devspaces_operator_ctl_src_enabled: false
# ocp4_workload_gitops_devspaces_operator_ctl_src_name: devspaces-operator
# ocp4_workload_gitops_devspaces_operator_ctl_src_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
# ocp4_workload_gitops_devspaces_operator_ctl_src_image_tag: v4.14_2024_05_20
# ocp4_workload_gitops_devspaces_operator_ctl_src_namespace: openshift-operators
# ocp4_workload_gitops_devspaces_operator_channel: stable
# ocp4_workload_gitops_devspaces_operator_namespace: openshift-operators
# ocp4_workload_gitops_devspaces_operator_starting_csv: devspacesoperator.v3.13.0
