ocp4_workload_lb2221_aqua_reporef: "main"
ocp4_workload_lb2221_aqua_repourl: "https://github.com/computate-org/smart-aquaculture-rhsummit"
ocp4_workload_lb2221_aqua_ansible_path: "/home/{{ ansible_user }}/smart-aquaculture-rhsummit"
