---
openshift_cnv_namespace: "{{ sandbox_openshift_namespace | default(env_type + '-' + guid) }}"

# Naming of instances
openshift_cnv_instance_numeration: '%d'

# Delete device retry
openshift_cnv_delete_retries: 20
openshift_cnv_delete_delay: 60

# Retries and delay variable
openshift_cnv_retries: 6
openshift_cnv_delay: 10

# Remove X-Frame-Options header (to iframe apps, for example in showroom)
openshift_cnv_route_remove_x_frame_options_header: false

# Use host.guid.domain
openshift_cnv_legacy_routes: false
