---
workloads: []

ocp_dr_trident_starting_csv: "trident-operator.v25.6.2"
ocp_dr_trident_operator_channel: "stable"
ocp_dr_trident_helm_chart_version: "100.2506.0"

ocp_dr_trident_first_rosa_cidr: "10.0.0.0/16"
ocp_dr_trident_second_rosa_name: "dr-{{ guid }}"
ocp_dr_trident_second_rosa_cidr: "10.10.0.0/16"
ocp_dr_trident_second_rosa_compute_replicas: 2
ocp_dr_trident_second_rosa_version: "4.16.37"

ocp_dr_trident_second_rosa_binary_path: "/usr/local/bin"
ocp_dr_trident_second_rosa_installer_version: latest
ocp_dr_trident_second_rosa_installer_url: >-
  https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/rosa/{{ rosa_installer_version }}/rosa-linux.tar.gz

ocp_dr_trident_bastion_cidr: "192.168.0.0/16"

ocp_dr_trident_fsx_name1: PROD-FSXONTAP
ocp_dr_trident_fsx_name2: DR-FSXONTAP

ocp_dr_trident_fsx_storage_vm_name1: SVM1
ocp_dr_trident_fsx_storage_vm_name2: SVM2

ocp_dr_trident_policy_name1: ProdTridentIAMPolicy
ocp_dr_trident_policy_name2: DRTridentIAMPolicy

# Passwords will be generated.
# If hardcoding: Passwords must be between 8 and 128 characters in length, must contain at least one English letter
#                and one number, and must not contain the word 'admin'.
ocp_dr_trident_fsx_admin_password: ""
ocp_dr_trident_svm_admin_password: ""

# Name of the S3 Bucket to be created
ocp4_workload_dr_trident_s3_bucket_name: "bucket-{{ guid }}"
