---
- name: Create S3 bucket
  amazon.aws.s3_bucket:
    name: "{{ ocp_dr_trident_s3_bucket_name }}"
    state: present
    access_key: "{{ aws_access_key_id }}"
    secret_key: "{{ aws_secret_access_key }}"
    region: "{{ trident_one.aws_default_region }}"
    public_access:
      block_public_acls: false
      ignore_public_acls: false
      block_public_policy: false
      restrict_public_buckets: false
  register: r_bucket

- name: Debug bucket
  ansible.builtin.debug:
    var: r_bucket

- name: Apply bucket policy for public read/write access
  amazon.aws.s3_bucket:
    name: "{{ ocp_dr_trident_s3_bucket_name }}"
    state: present
    access_key: "{{ aws_access_key_id }}"
    secret_key: "{{ aws_secret_access_key }}"
    region: "{{ trident_one.aws_default_region }}"
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "PublicReadWrite",
                "Effect": "Allow",
                "Principal": "*",
                "Action": [
                    "s3:GetObject",
                    "s3:PutObject",
                    "s3:DeleteObject",
                    "s3:ListBucket"
                ],
                "Resource": [
                   "arn:aws:s3:::{{ ocp_dr_trident_s3_bucket_name }}/*",
                   "arn:aws:s3:::{{ ocp_dr_trident_s3_bucket_name }}"
                ]
            }
        ]
      }

- name: Save AgnosticD A3 Bucket data
  agnosticd_user_info:
    data:
      s3_bucket_name: "{{ ocp_dr_trident_s3_bucket_name }}"
      s3_bucket_region: "{{ trident_one.aws_default_region }}"
