---

- name: Include destroy tasks
  ansible.builtin.include_tasks:
    file: destroy.yml
  when: ACTION == "destroy"

- name: Include provision tasks  
  ansible.builtin.include_tasks:
    file: provision.yml
  when: (ACTION == "create" or ACTION == "provision")
