galaxy_info:
  author: 
    - Patrick Rutledge
    - Tony Kay
  description: Deploy IBM InstructLab service with associated IBM Cloud resources using Terraform
  company: Red Hat
  
  issue_tracker_url: https://github.com/redhat-cop/agnosticd/issues
  
  license: Apache-2.0
  
  min_ansible_version: "2.12"
  
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "38"
        - "39"
        - "40"
    - name: Ubuntu
      versions:
        - "20.04"
        - "22.04"
  
  galaxy_tags:
    - ibm
    - cloud
    - instructlab
    - ai
    - terraform
    - agnosticd
    - deployment
    - automation

dependencies: []
