---
# ocp_username can be set by the provisioner if the workload is applied to a
# shared cluster to set up for the requesting user.
# The default, "system:admin", is not used for roles that are deployed as part of a whole
# OpenShift cluster provision run.
ocp_username: "system:admin"

# OSC version tag
ocp4_workload_coco_on_aro_osc_version: "latest"

# Verity image base name
ocp4_workload_coco_on_aro_verity_image: "registry.redhat.io/openshift-sandboxed-containers/osc-dm-verity-image"

# Image to pull to podvm (will be determined dynamically if not set)
# Format: registry.redhat.io/openshift-sandboxed-containers/osc-dm-verity-image@sha256:...
ocp4_workload_coco_on_aro_image: ""

# Path to cluster pull secret file (relative to working directory or absolute path)
ocp4_workload_coco_on_aro_authfile: "cluster-pull-secret.json"
