---
- name: Allow {{ __allow_ip }} access in security group {{ __security_group.group_name }}
  amazon.aws.ec2_security_group:
    name: "{{ __security_group.group_name }}"
    description: "{{ __security_group.description }}"
    purge_egress_rules: false
    purge_rules: false
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: "{{ __allow_ip }}/32"
        rule_desc: "Ansible controller access"
    access_key: "{{ aws_access_key_id }}"
    secret_key: "{{ aws_secret_access_key }}"
    vpc_id: "{{ __security_group.vpc_id }}"
    region: "{{ aws_region }}"
...
