---

service_vm_jupyter_lab_domain_name: "bastion.{{ guid }}{{ subdomain_base_suffix }}" 

service_vm_jupyter_lab_jupyter_user: "{{ student_name }}"
service_vm_jupyter_lab_jupyter_group: "users"
service_vm_jupyter_lab_jupyter_directory: "/home/{{ student_name }}/lab"
service_vm_jupyter_lab_jupyter_ssl_dir: "/home/{{ service_vm_lab_juypter_user }}/.jupyter/ssl"
service_vm_jupyter_lab_jupyter_port: 9443
service_vm_jupyter_lab_jupyter_theme: "JupyterLab Dark"

service_vm_jupyter_lab_jupyter_pip_packages:
  - jupyter
  - jupyterlab_pygments
  - jupyter-lsp

# Consider jupyterlab-vim if vim makes a good choice?

service_vm_jupyter_lab_certbot_email: "dev-user@opentlc.com"