- name: Running Pre Workload Tasks PING
  ansible.builtin.include_tasks:
    file: ./workload_init.yaml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload Tasks
  ansible.builtin.include_tasks:
    file: ./workload_main.yaml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "create" or ACTION == "provision"

- name: Running Workload removal Tasks
  ansible.builtin.include_tasks:
    file: ./workload_remove.yaml
    apply:
      become: "{{ become_override | bool }}"
  when: ACTION == "destroy" or ACTION == "remove"