---

- name: Evaluate {{ operators_project }} namespace if not exists
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ operators_project }}'
    state: present

- name: Evaluate OpenShift Dev Spaces Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'devspaces-subscription.yaml.j2') }}"

- name: "Wait until InstallPlan is available"
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: "{{ operators_project }}"
    name: devspaces
  register: sub
  retries: 30
  delay: 10
  until:
    - sub.resources[0].status.installplan.name is defined

- name: Approve InstallPlan
  shell:
    cmd: >
      oc patch installplan {{ sub.resources[0].status.installplan.name }}
      -n {{ operators_project }}  --type=json -p='[{"op": "replace", "path": "/spec/approved", "value": true}]'

- name: Wait until devspaces-operator is up
  k8s_info:
    api_version: v1
    kind: Deployment
    name: devspaces-operator
    namespace: '{{ operators_project }}'
  register: pod_list
  until: pod_list|json_query('resources[*].status.readyReplicas')|unique == [1]
  retries: 10
  delay: 30

- name: Evaluate {{ che_project }} namespace if not exists
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ che_project }}'
    state: present

- name: Evaluate OpenShift Dev Spaces Cluster
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'devspaces-cluster.yaml.j2') }}"
