# CheCluster needs to be active before provisioning workspaces.
# Otherwise the workspaces will fail as they need to comunicate with the CheCluster dashboard.
- name: "Wait until CheCluster is active"
  k8s_info:
    api_version: org.eclipse.che/v2
    kind: CheCluster
    namespace: '{{ che_project }}'
    name: devspaces
  register: cc
  retries: 30
  delay: 10
  until:
    - cc.resources[0].status.chePhase is defined
    - cc.resources[0].status.chePhase == "Active"

- name: Provision User Namespaces for {{ num_users }} users
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'user-projects.yaml.j2') }}"
  retries: 10
  delay: 30

- name: Give users access to projects for {{ num_users }} users
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'user-rolebinding.yaml.j2') }}"
  vars:
    bindings:
      - namespace: "user-devspaces"
        role: "admin"
  retries: 15
  delay: 30

- name: Create DevWorkspace for {{ num_users }} users
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'user-devworkspace.yaml.j2') }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: __user  # Overrides the default 'item' with '__user' for template rendering
    pause: 1  # Seconds to wait between each iteration
  retries: 15
  delay: 30
