- name: Collect DevWorkspaces
  k8s_info:
    api_version: workspace.devfile.io/v1alpha2
    kind: DevWorkspace
  register: dw_list

- name: Print dw_list
  debug:
    msg: "number of DevWorkspaces to delete: {{ dw_list.resources|length }}"

# - name: Print dw_list
#   debug:
#     msg: "DevWorkspaces to delete: {{ item.metadata.namespace }}"
#   loop: '{{ dw_list.resources }}'

- name: Delete DevWorkspaces
  k8s:
    state: absent
    api_version: workspace.devfile.io/v1alpha2
    kind: DevWorkspace
    name: '{{ item.metadata.name }}'
    namespace: '{{ item.metadata.namespace }}'
  loop: '{{ dw_list.resources }}'