---
become_override: false
silent: false

# general name used by microshift resources.
ocp4_workload_microshift_name: microshift
# namespace for kubevirt vm and related resources.
ocp4_workload_microshift_vm_namespace: microshift-001
# name used by RHACM for cluster management.
ocp4_workload_microshift_cluster_name: "{{ ocp4_workload_microshift_vm_namespace }}-cluster"

ocp4_workload_microshift_bastion_user: "{{ student_name | default(ansible_user) }}"

# YOU NEED TO SET ONE OF THE FOLLOWING:
# Set this if you want to download the image from a public URL with no authentication
# ocp4_workload_microshift_vm_image: https://gpte-public.s3.amazonaws.com/microshift/rhel87-microshift-latest.img

# S3 configuration for private bucket access
# If these variables are defined, the role will download the image from S3 instead of using the public URL
# ocp4_workload_microshift_s3_access_key: "your-aws-access-key"
# ocp4_workload_microshift_s3_secret_key: "your-aws-secret-key"
# ocp4_workload_microshift_s3_region: "us-east-1"
# ocp4_workload_microshift_vm_image: https://s3.us-east-1.amazonaws.com/rhdp-images/rhel96-microshift419.qcow2

# ocp4_workload_microshift_cleanup_downloaded_image: false  # Set to true to remove downloaded image after VM creation
ocp4_workload_microshift_vm_ssh_key: "/home/{{ ocp4_workload_microshift_bastion_user }}/.ssh/{{ ocp4_workload_microshift_vm_namespace }}"
ocp4_workload_microshift_vm_kubeconfig: /home/{{ ocp4_workload_microshift_bastion_user }}/.kube/{{ ocp4_workload_microshift_vm_namespace }}

# size of the disk used by microshift storage, where the pods pvcs will stay.
# this is not the rhel root disk size.
ocp4_workload_microshift_disk_size: 10Gi
# name of the disk used by microshift storage, also the name of the backing pvc.
ocp4_workload_microshift_disk_name: rhel96-microshift-mshiftdisk

# helm chart repo for the app that is deployed on microshift in the edge.
ocp4_workload_microshift_app_repo: https://redhat-gpte-devopsautomation.github.io/microshift
# app image that is deployed on microshift in the edge.
ocp4_workload_microshift_app_image: quay.io/microshift/hello-microshift:latest
# namespace created on microshift in the edge (must not be 'hello-microshift').
ocp4_workload_microshift_app_namespace: demo-microshift
