---
- name: Apply RHSI Plugin CRD
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'rhsi-openshift-plugin.yaml.j2') }}"
  register: manifest_result

- name: Display manifest application result
  debug:
    var: manifest_result
    verbosity: 1

- name: Get current console configuration
  k8s_info:
    api_version: operator.openshift.io/v1
    kind: Console
    name: cluster
  register: console_info

- name: Set fact for combined plugins
  set_fact:
    combined_plugins: "{{ (console_info.resources[0].spec.plugins | default([])) + ['openshift-site-plugin'] | unique }}"

- name: Update console with combined plugins
  k8s:
    state: present
    api_version: operator.openshift.io/v1
    kind: Console
    name: cluster
    merge_type: merge
    definition:
      spec:
        plugins: "{{ combined_plugins }}"
