---
- name: Create OpenShift Objects for jaeger
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/jaeger_subscription.yaml

- name: wait for the status of the Jaeger subscription to not be empty
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: jaeger
    namespace: openshift-operators
  register: jaeger_subscription_out
  until:
    - jaeger_subscription_out is defined
    - jaeger_subscription_out.resources is defined
    - jaeger_subscription_out.resources[0] is defined
    - jaeger_subscription_out.resources[0].status is defined
    - jaeger_subscription_out.resources[0].status.installplan is defined
  retries: 30
  delay: 20

- name: patch the installplan to approve it
  k8s:
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: InstallPlan
      metadata:
        namespace: openshift-operators
        name: "{{ jaeger_subscription_out.resources[0].status.installplan.name }}"
      spec:
        approved: true

- name: Wait for Jaeger CRD
  k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: jaegers.jaegertracing.io
  register: r_jaeger_crd
  retries: 200
  delay: 10
  until: r_jaeger_crd.resources | list | length == 1


