---
- name: Step 00xxxxx software
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step005
    - software

  tasks:

    - name: "Software tasks Started"
      ansible.builtin.debug:
        msg: "Software tasks Started"

- name: Install packages defined in the instances
  hosts: all:!isolated
  gather_facts: false
  become: true
  tasks:
    - name: Setup Red Hat packages for each host
      when: instances | selectattr('name', 'equalto', ansible_host ) | selectattr('packages', 'defined') | map(attribute='packages') | default([]) | list | length > 0
      ansible.builtin.dnf:
        state: present
        name: "{{ instances | selectattr('name', 'equalto', ansible_host ) | map(attribute='packages') | from_yaml | flatten }}"
      register: r_dnf_packages
      until: r_dnf_packages is succeeded
      retries: 5
      delay: 10


# ----------------------------------------------------------------------
# Software Workloads as role
# ----------------------------------------------------------------------
- name: Import Software workloads
  import_playbook: workloads.yml
  vars:
    _workload_title_: "Software"
    _workloads_: "{{ software_workloads | default([]) }}"

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:

    - name: "Software checks completed successfully"
      ansible.builtin.debug:
        msg: "Software checks completed successfully"

- name: Run software_validation playbook
  when: >-
    agd_software_validation | default(false) | bool
      or agd_validation | default(false) | bool
  ansible.builtin.import_playbook: software_validation.yml
  tags:
    - software_validation
    - agd_validation
...
