---
# IBM Cloud Regional Configuration
# InstructLab service is only available in us-east region - hardcoded in tasks

# Terraform Configuration
ibmcloud_terraform_dir: "{{ output_dir }}"
ibmcloud_terraform_version: "1.9.8"
ibmcloud_provider_version: "1.80.4"
ibmcloud_terraform_name_prefix: "instructlab"

# Storage Configuration
ibmcloud_storage_class: standard

# InstructLab Service Configuration
ibmcloud_instructlab_instance_service: "instructlab"
ibmcloud_instructlab_instance_plan: "instructlab-pricing-plan"