# role
become_override: false
ocp_username: "{{ocp4_workload_authentication_admin_user|default('opentlc-mgr',true)}}"
silent: false

openshift_version: "{{ ocp_version }}"

# For Tech Preview Enablement
mcp_name: "worker"  # MachineConfigPool to monitor (e.g., 'worker' or 'master')
timeout_seconds: 3600  # Total timeout for the playbook
poll_interval: 30  # Polling interval for API and status checks
api_timeout: 600  # Timeout for API availability/unavailability checks
api_poll_interval: 10  # Polling interval for API checks
oc_command: "oc"  # Path to oc command, adjust if needed
feature_gate_patch: >
  {"spec":{"featureSet":"CustomNoUpgrade","customNoUpgrade":{"enabled":["ProcMountType","UserNamespacesSupport","UserNamespacesPodSecurityStandards"]}}}

# ======================
cli_jbang: /home/runner/.jbang/bin/jbang
cli_camel: /home/runner/.jbang/bin/jbang run camel@apache/camel
cli_camel_routes: /runner/project/roles_ocp_workloads/ocp4-workload-camel-workshop/deploy/camel
# ======================

# provision_webapp
webapp_operator_release_tag: '0.0.63-workshop-1'
webapp_client_id: tutorial-web-app
ocp4_workload_webapp_group_name: dedicated-admins
webapp_operator_template_path: /home/tutorial-web-app-operator/deploy/template/tutorial-web-app.yml
webapp_operator_resources: 'https://github.com/hguerrero/tutorial-web-app-operator/archive/v{{webapp_operator_release_tag}}.zip'
webapp_operator_resource_items:
  - rbac.yaml
  - sa.yaml
  - crd.yaml
  - operator.yaml
webapp_walkthrough_locations:
  - 'https://github.com/RedHat-Middleware-Workshops/camel-workshop-docs?walkthroughsFolder=/docs/labs/#{{workshop_git_branch}}'

# variable for agV
workshop_docs_git_branch: main

# Workshop repo variables
workshop_git_repo: 'https://github.com/RedHat-Middleware-Workshops/camel-workshop-workspace'
workshop_git_branch: "main"
