---
# -------------------------------------------------------------
# Create an Azure federated identity credential linking the
# service account in OpenShift Container Platform to the Azure user-assigned managed identity.
# -------------------------------------------------------------
open_env_azure_aro_ai_search_federated_app_id: "f1dd0a37-89c6-4e07-bcd1-ffd3d43d8875"
open_env_azure_aro_ai_search_federated_id_cred_name: "{{ azure_resource_group }}-identity"
open_env_azure_aro_ai_search_sa_namespace: "user"
open_env_azure_aro_ai_search_sa_name: "my-workbench"
open_env_azure_aro_ai_search_location: "eastus"
open_env_azure_aro_ai_search_user_ai_sub: "{{ azure_subscription_id }}"
open_env_azure_aro_ai_search_user_ai_rg: "rhdp-ai"
open_env_azure_aro_ai_search_user_ai_search_name: "parasol-workshop-search"
open_env_azure_aro_ai_search_user_ai_name: "llm-gpt4-lightspeed"