# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "rhintegration.demo"
# public_baseurl: "https://synapse-service-matrix.apps.cluster-svdnn.svdnn.sandbox758.opentlc.com"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false

database:
  name: sqlite3
  args:
    database: /data/homeserver.db

# database:
#  name: psycopg2
#  allow_unsafe_locale: true
#  args:
#    user: synapse-db
#    password: synapse
#     database: synapse
#     host: postgres-service.test.svc.cluster.local
#     cp_min: 5
#     cp_max: 10

# rate limiting
# rateliming:
rc_login:
  address:
    per_second: 1000
    burst_count: 10000
  account:
    per_second: 1000
    burst_count: 10000
  failed_attempts:
    per_second: 1000
    burst_count: 10000

rc_message:
  per_second: 50
  burst_count: 50


log_config: "/data/rhintegration.demo.log.config"
media_store_path: /data/media_store
registration_shared_secret: "BtDaMSiDS-B:V2KP-_QoGgGu,FwK~9zKfL8Ow3=g;xHAm4GR=r"
report_stats: false
macaroon_secret_key: "+Ysdz_s*7tOL0j0P&kF^@hA_wQ6SLeV6ciwxR4*f3n&HM;7fN1"
form_secret: "@RzaZ;NsJT1QueIgSVzw,0IhNxPf3atW_ItNXTfUIzB9:5RP4~"
signing_key_path: "/data/rhintegration.demo.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"

enable_group_creation: true

# vim:ft=yaml