apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  platform:
    graph: false
    channels:
    - name: stable-4.18
      minVersion: 4.18.3
      maxVersion: 4.18.4
    architectures:
    - amd64
  additionalImages:
  - name: quay.io/karmab/curl:multi
  - name: quay.io/karmab/origin-coredns:multi
  - name: quay.io/karmab/haproxy:multi
  - name: quay.io/karmab/origin-keepalived-ipfailover:multi
  - name: quay.io/karmab/mdns-publisher:multi
  - name: quay.io/karmab/kubectl:multi
  - name: registry.redhat.io/openshift4/ztp-site-generate-rhel8:v4.18.0-39
  - name: quay.io/rhsysdeseng/lab5gran:v4.18.4
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18-1742933492
    packages:
    - name: advanced-cluster-management
      channels:
      - name: release-2.13
    - name: multicluster-engine
      channels:
      - name: stable-2.8
    - name: topology-aware-lifecycle-manager
      channels:
      - name: stable
    - name: openshift-gitops-operator
      channels:
      - name: latest
    - name: lvms-operator
      channels:
      - name: stable-4.18
    - name: sriov-network-operator
      channels:
      - name: stable
    - name: lifecycle-agent
      channels:
      - name: stable
    - name: redhat-oadp-operator
      channels:
      - name: stable-1.4
