apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  platform:
    graph: false
    channels:
    - name: stable-4.19
      minVersion: 4.19.0
      maxVersion: 4.19.1
    architectures:
    - amd64
  additionalImages:
  - name: quay.io/karmab/curl:multi
  - name: quay.io/karmab/origin-coredns:multi
  - name: quay.io/karmab/haproxy:multi
  - name: quay.io/karmab/origin-keepalived-ipfailover:multi
  - name: quay.io/karmab/mdns-publisher:multi
  - name: quay.io/karmab/kubectl:multi
  - name: registry.redhat.io/openshift4/ztp-site-generate-rhel8:v4.19.0-1
  - name: registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9:2.14.0-1
  - name: quay.io/rhsysdeseng/lab5gran:v4.19.1
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.19-1754067857
    packages:
    - name: advanced-cluster-management
      channels:
      - name: release-2.14
    - name: multicluster-engine
      channels:
      - name: stable-2.9
    - name: topology-aware-lifecycle-manager
      channels:
      - name: stable
    - name: openshift-gitops-operator
      channels:
      - name: latest
    - name: lvms-operator
      channels:
      - name: stable-4.19
    - name: sriov-network-operator
      channels:
      - name: stable
    - name: lifecycle-agent
      channels:
      - name: stable
    - name: redhat-oadp-operator
      channels:
      - name: stable
    - name: ptp-operator
      channels:
      - name: stable
    - name: cluster-logging
      channels:
      - name: stable-6.3
    - name: loki-operator
      channels:
      - name: stable-6.3
