---
- ansible.builtin.include_role:
    name: infra-cloud-tags
  when: cloud_tags_final is not defined

- set_fact:
    r_openshift_cnv_containers: []

- name: Create Containers
  loop: "{{ containers | default([]) }}"
  loop_control:
    loop_var: _container
  ansible.builtin.include_tasks: create_container.yaml



