---
become_override: false
ocp_username: admin
silent: false

ocp4_workload_advanced_developer_suite_tssc_namespace: tssc

ocp4_workload_advanced_developer_suite_tssc_cli_repo: https://github.com/redhat-appstudio/rhtap-cli
ocp4_workload_advanced_developer_suite_tssc_cli_revision: release-1.6

ocp4_workload_advanced_developer_suite_keycloak_namespace: tssc-keycloak
ocp4_workload_advanced_developer_suite_dh_namespace: tssc-dh

ocp4_workload_advanced_developer_suite_user_base_name: user
ocp4_workload_advanced_developer_suite_user_password: password
ocp4_workload_advanced_developer_suite_user_count: "{{ num_users | default(1) }}"

ocp4_workload_advanced_developer_suite_admin_user: admin
ocp4_workload_advanced_developer_suite_admin_password: password
ocp4_workload_advanced_developer_suite_remove_kubeadmin: true

ocp4_workload_advanced_developer_suite_openshift_keycloak_client_id: idp-4-ocp
ocp4_workload_advanced_developer_suite_openshift_keycloak_client_secret: password
ocp4_workload_advanced_developer_suite_dh_keycloak_client_id: rhdh
ocp4_workload_advanced_developer_suite_dh_keycloak_client_secret: password
ocp4_workload_advanced_developer_suite_dh_dynamic_plugins_enable:
- package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
  disabled: false
- package: ./dynamic-plugins/dist/backstage-community-plugin-ocm
  disabled: false
- package: ./dynamic-plugins/dist/backstage-community-plugin-ocm-backend-dynamic
  disabled: false

ocp4_workload_advanced_developer_suite_dh_orchestrator_enabled: true
ocp4_workload_advanced_developer_suite_dh_orchestrator_plugins_enable:
- disabled: false
  package: "@redhat/backstage-plugin-orchestrator-backend-dynamic@1.5.1"
  integrity: sha512-VIenFStdq9QvvmgmEMG8O7b2wqIebvEcqNeJ9SWZ8jen9t+efTK6D3Rde74LQ1no1QaHLx8RoxNCOuTUEF8O/g==
  pluginConfig:
    orchestrator:
      dataIndexService:
        url: http://sonataflow-platform-data-index-service.sonataflow-infra
- disabled: false
  package: "@redhat/backstage-plugin-orchestrator@1.5.1"
  integrity: sha512-7VOe+XGTUzrdO/av0DNHbydOjB3Lo+XdCs6fj3JVODLP7Ypd3GXHf/nssYxG5ZYC9F1t9MNeguE2bZOB6ckqTA==
  pluginConfig:
    dynamicPlugins:
      frontend:
        red-hat-developer-hub.backstage-plugin-orchestrator:
          appIcons:
          - importName: OrchestratorIcon
            module: OrchestratorPlugin
            name: orchestratorIcon
          dynamicRoutes:
          - importName: OrchestratorPage
            menuItem:
              icon: orchestratorIcon
              text: Orchestrator
            module: OrchestratorPlugin
            path: /orchestrator
- disabled: false
  package: "@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic@1.5.1"
  integrity: sha512-bnVQjVsUZ470Vgm2kd5Lo/bVa2fF0q4GufBDc/8oTQsnP3zZJQqKFvFElBTCjY76RqkECydlvZ1UFybSzvockQ==
  pluginConfig:
    orchestrator:
      dataIndexService:
        url: http://sonataflow-platform-data-index-service.sonataflow-infra
- disabled: false
  package: "./dynamic-plugins/dist/backstage-plugin-notifications"
- disabled: false
  package: "./dynamic-plugins/dist/backstage-plugin-signals"
- disabled: false
  package: "./dynamic-plugins/dist/backstage-plugin-notifications-backend-dynamic"
- disabled: false
  package: "./dynamic-plugins/dist/backstage-plugin-signals-backend-dynamic"

ocp4_workload_advanced_developer_suite_gitlab_namespace: gitlab
ocp4_workload_advanced_developer_suite_dh_catalog_locations:
  repository: tssc-developer-hub-configuration
  branch: main
  group: rhdh
  file: all-locations.yaml

ocp4_workload_advanced_developer_suite_devspaces_namespace: openshift-devspaces

ocp4_workload_advanced_developer_suite_quay_namespace: quay-enterprise
ocp4_workload_advanced_developer_suite_quay_org_name: tssc
ocp4_workload_advanced_developer_suite_quay_admin_user: quayadmin
ocp4_workload_advanced_developer_suite_quay_admin_password: "{{ common_password | default('password') }}"

ocp4_workload_advanced_developer_suite_tssc_ci_namespace: tssc-app-ci

ocp4_workload_advanced_developer_suite_nginx_namespace: nginx

ocp4_workload_advanced_developer_suite_tssc_gitops_namespace: tssc-gitops

ocp4_workload_advanced_developer_suite_tssc_tpa_namespace: tssc-tpa

ocp4_workload_advanced_developer_suite_jenkins_namespace: jenkins
ocp4_workload_advanced_developer_suite_jenkins_admin_user: admin
ocp4_workload_advanced_developer_suite_jenkins_admin_password: password

ocp4_workload_advanced_developer_suite_acs_namespace: tssc-acs
ocp4_workload_advanced_developer_suite_acs_admin_user: admin

ocp4_workload_advanced_developer_suite_disable_odf: false