---
- name: Set environment variable HF_TOKEN
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: "HF_TOKEN={{ hf_token }}"
    regexp: "^HF_TOKEN="
    state: present
  become: true

- name: Ensure nvidia-ctk is available
  ansible.builtin.stat:
    path: /usr/bin/nvidia-ctk
  register: nvidia_ctk_stat

- name: Ensure the nvidia-ctk is executable
  ansible.builtin.file:
    path: /usr/bin/nvidia-ctk
    mode: '0755'
  when: nvidia_ctk_stat.stat.exists

- name: Ensure CDI directory exists
  ansible.builtin.file:
    path: /etc/cdi
    state: directory
    mode: '0755'
  become: true

- name: Generate nvidia CDI configuration
  ansible.builtin.command:
    cmd: nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
  become: true
  args:
    creates: /etc/cdi/nvidia.yaml

- name: Create vLLM cache directory
  ansible.builtin.file:
    path: "{{ vllm_cache_dir }}"
    state: directory
    mode: '0777'
  become: true
  become_user: "{{ vllm_user }}"

- name: Set vm.overcommit_memory parameter
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: '1'
    state: present
    reload: true
  become: true

- name: Configure container registry authentication
  ansible.builtin.include_tasks: configure_registry_auth.yml
  when: registry_auth_enabled | bool

- name: Create vLLM systemd service
  ansible.builtin.include_tasks: create_systemd_service.yml
