---
galaxy_info:
  role_name: ocp4_workload_showroom_ocp_integration
  author: Alberto Gonzalez
  description: |
    Tweak/Hack OCP to be embedded in iframes
  license: MIT
  min_ansible_version: "2.9"
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
dependencies: []
