# example agnosticv settings.
# This one applies a machineconfig via igintion
# You could use this same array to apply other iginition configs
# not just machineconfigs.

# ai_machineconfigs:
# - apiVersion: machineconfiguration.openshift.io/v1
#   kind: MachineConfig
#   metadata:
#     labels:
#       machineconfiguration.openshift.io/role: worker
#     name: 99-openshift-machineconfig-worker-psi-karg
#   spec:
#     kernelArguments:
#     - psi=1
