---
- name: Create DDNS secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'secret-tsig-creds.yaml.j2') }}"
  register: r_ddns_secret
  retries: 10
  delay: 60
  until: r_ddns_secret is success
