---
become_override: true
ocp_username: opentlc-mgr
silent: false
lab_version: "lab-4.20"
lab_release: "4.20"
repo_user: "RHsyseng"
platform_demo_redhat_com: true
student_name: "lab-user"
# yamllint disable rule:line-length
kcli_rpm: "https://github.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab/releases/download/{{ lab_release }}/kcli-99.0.0.git.202602040650.86cacd3-0.el9.x86_64.rpm"
lab_repo: "https://github.com/{{ repo_user }}/5g-ran-deployments-on-ocp-lab.git"
# yamllint enable rule:line-length
ocp4_major_release: "4.20"
ocp4_minor_release: "4.20.10"
lab_network_cidr: "192.168.125.0/24"
lab_network_domain: "5g-deployment.lab"
lab_sriov_domain: "sriov-network.lab"
lab_ptp_domain: "ptp-network.lab"
lab_sriov_cidr: "192.168.100.0/24"
lab_ptp_cidr: "192.168.200.0/24"
lab_registry_host: "infra.5g-deployment.lab:8443"
lab_api_host: "api.hub.5g-deployment.lab:6443"
upstream_dns: "1.1.1.1"
disconnected_update: false
download_rhcos_isos: false
install_lab_dependencies: false
hypervisor_min_memory_mb: 204800
# hypervisor_min_cpus: 128
hypervisor_min_cpus: 64
hypervisor_supported_distributions: ['RedHat', 'CentOS', 'Fedora']
lab_hub_vm_cpus: 16
lab_hub_vm_memory: 48000
lab_hub_vm_disk: 200
lab_sno_vm_cpus: 12
lab_sno_vm_memory: 24000
lab_sno_vm_disk: 200
extra_disk_libvirt_images: true
disconnected_catalog_image: infra.5g-deployment.lab:8443/redhat/redhat-operator-index:v4.20-1769431701
# yamllint disable rule:line-length
rhcos_live_image: 'rhcos-4.20.0-x86_64-live-iso.x86_64.iso'
rhcos_rootfs_image: 'rhcos-4.20.0-x86_64-live-rootfs.x86_64.img'
rhcos_live_image_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.20/4.20.0/{{ rhcos_live_image }}"
rhcos_rootfs_image_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.20/4.20.0/{{ rhcos_rootfs_image }}"
lab_url: "https://labs.sysdeseng.com/5g-ran-deployments-on-ocp-lab/{{ ocp4_major_release }}/index.html"
# yamllint enable rule:line-length
