---
- name: Create vault secrets for TPA
  when:
  - registry_redhat_io_docker_config is defined
  - registry_redhat_io_docker_config | length > 0
  kubernetes.core.k8s_exec:
    namespace: "{{ ocp4_workload_trusted_application_pipeline_vault_namespace }}"
    pod: vault-0
    command: vault kv put kv/secrets/janusidp/tas/registry_redhat_io_docker_config value={{ registry_redhat_io_docker_config }}