apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: community-operators-index
  namespace: openshift-marketplace
spec:
  displayName: Community Operators Index 4.18
  image: 'quay.io/gpte-devops-automation/olm_snapshot_community_catalog:v4.18_2025_04_21'
  publisher: Daniel Oh
  sourceType: grpc