apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: community-operators-index
  namespace: openshift-marketplace
spec:
  displayName: Community Operators Index 4.20
  image: 'quay.io/gpte-devops-automation/olm_snapshot_community_catalog:v4.20_2025_12_15'
  publisher: Daniel Oh
  sourceType: grpc
