---
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-operators
  annotations:
    che.eclipse.org/checluster-defaults-cleanup: '{"spec.components.pluginRegistry.openVSXURL":"true"}'
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    database:
      credentialsSecretName: postgres-credentials
      externalDb: false
      postgresDb: dbche
      postgresHostName: postgres
      postgresPort: '5432'
      pvc:
        claimSize: 1Gi
    metrics:
      enable: true
    pluginRegistry: {openVSXURL: 'https://open-vsx.org'}
    imagePuller:
      enable: true
      spec:
        images: quarkus-stack-3-20=quay.io/openshiftlabs/quarkus-workshop-stack:3.20;vscode=registry.redhat.io/devspaces/code-rhel9@sha256:e0d94b772b364b41f419e144042766579bd2ef9c1fe5259c0defaff6b5169718;project-cloner=registry.redhat.io/devworkspace/devworkspace-project-clone-rhel9@sha256:63843bb17c34ee71dc801626f829190e53917455564e5a20b4a48ca2d95a8959
  containerRegistry: {}
  devEnvironments:
    secondsOfRunBeforeIdling: -1
    defaultNamespace:
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: -1
    storage:
      pvcStrategy: per-user
  networking: {}
