apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators-index
  namespace: openshift-marketplace
spec:
  displayName: Red Hat Operators Index 4.19
  image: 'quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog:v4.19_2025_08_18'
  publisher: Daniel Oh
  sourceType: grpc
