---
become_override: False
ocp_username: opentlc-mgr
silent: False

num_users: 5
workshop_openshift_user_name: userXX
workshop_openshift_user_password: 'openshift'
workshop_ds_user_name: userXX
workshop_ds_user_password: 'openshift'
workshop_openshift_admin_password: 'r3dh4t1!'
workshop_rhsso_admin_user_name: admin
workshop_rhsso_admin_password: 'r3dh4t1!'
workshop_content_git_tag: 'rhbq-3.27'
workshop_content_git_org: 'RedHat-Middleware-Workshops'
community_catalog_source_tag: 'v4.20_2025_12_15'
redhat_catalog_source_tag: 'v4.20_2025_12_15'
devspaces_images_list: >-
  quarkus-stack-3-27=quay.io/openshiftlabs/quarkus-workshop-stack:3.27-ocp-4.20;
  che-code-injector=registry.redhat.io/devspaces/code-rhel9@sha256:e0d94b772b364b41f419e144042766579bd2ef9c1fe5259c0defaff6b5169718;
  project-clone=registry.redhat.io/devworkspace/devworkspace-project-clone-rhel9@sha256:63843bb17c34ee71dc801626f829190e53917455564e5a20b4a48ca2d95a8959;

module_type: m1

#
# All modules. Do NOT use a comma (,) in the titles or paths!
#
module_titles:
  - { name: m1, title: "Basic Quarkus Development", path: /workshop/quarkus-lab/lab/intro }
  - { name: m2, title: "Advanced Quarkus Development", path: /workshop/quarkus-lab/lab/extensions }
  - { name: m3, title: "Quarkus for Spring Developers", path: /workshop/quarkus-lab/lab/springenv }
