---
# Implement your Workload deployment tasks here

- name: Ensure management cluster is deployed via kcli
  ansible.builtin.shell:
    cmd: kcli create cluster openshift --pf management.yml
  args:
    chdir: /root/mgmt-cluster-install/
  register: result
  failed_when: result.rc != 0 and ("Remove existing directory" not in result.stderr)

- name: Remove kubeadmin user
  kubernetes.core.k8s:
    kubeconfig: /root/.kcli/clusters/management/auth/kubeconfig
    state: absent
    api_version: v1
    kind: Secret
    namespace: kube-system
    name: kubeadmin

- name: Wait until LVMCluster is ready
  kubernetes.core.k8s_info:
    kubeconfig: /root/.kcli/clusters/management/auth/kubeconfig
    api_version: lvm.topolvm.io/v1alpha1
    kind: LVMCluster
    name: lvmcluster
    namespace: openshift-storage
  register: lvmcluster
  retries: 60
  delay: 10
  until:
    - lvmcluster is defined
    - lvmcluster.resources is defined and lvmcluster.resources | length > 0 and lvmcluster.resources[0].status.state == "Ready"


- name: Ensure LVMCLuster storageclass is set as default
  kubernetes.core.k8s:
    kubeconfig: /root/.kcli/clusters/management/auth/kubeconfig
    state: patched
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: lvms-vg1
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
  register: result
  until: result.failed != true
  retries: 5
  delay: 60

- name: Wait until MetalLB is ready
  kubernetes.core.k8s_info:
    kubeconfig: /root/.kcli/clusters/management/auth/kubeconfig
    api_version: metallb.io/v1beta1
    kind: MetalLB
    name: metallb
    namespace: openshift-operators
  register: metallb
  retries: 60
  delay: 10
  until:
    - metallb is defined
    - metallb.resources | length > 0
    - metallb.resources[0].status.conditions | json_query(metallb_query) == "False"
  vars:
    metallb_query: >-
      [?type=='Progressing'].status[] | [0]

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
