---

- name: Get current console configuration
  k8s_info:
    api_version: operator.openshift.io/v1
    kind: Console
    name: cluster
  register: console_info
  retries: 10
  delay: 30
  ignore_errors: true
  until:
  - console_info is not failed
  - console_info.resources[0].spec.plugins is defined
  - console_info.resources[0].spec.plugins | length > 0

- name: Print console_info from the previous task
  ansible.builtin.debug:
    var: console_info

- name: Set fact for combined plugins
  set_fact:
    combined_plugins: "{{ (console_info.resources[0].spec.plugins | default([])) + ['kuadrant-console-plugin', 'openshift-site-plugin'] | unique }}"

- name: Update console with combined plugins
  k8s:
    state: present
    api_version: operator.openshift.io/v1
    kind: Console
    name: cluster
    merge_type: merge
    definition:
      spec:
        plugins: "{{ combined_plugins }}"
      retries: 10
  delay: 30
  ignore_errors: true
  register: console_update_result
  until: console_update_result is not failed
