---
galaxy_info:
  role_name: ocp4_workload_lb2221_aqua
  author:
  - Judd Maltin <judd@redhat.com>
  description: |
    Deploys all components and users for the Summit 2025 session
  platforms: []
  license: GNU General Public License v3.0
  galaxy_tags:
  - ocp4
  - openshift
dependencies: []
