---
_ocp4_workload_lb2739_fsx_admin_password: ""
_ocp4_workload_lb2739_svm_admin_password: ""

_ocp4_workload_lb2739_second_rosa_openshift_api_url: ""
_ocp4_workload_lb2739_second_rosa_openshift_console_url: ""
_ocp4_workload_lb2739_second_rosa_cluster_admin_password: ""
_ocp4_workload_lb2739_second_rosa_cluster_admin_token: ""
