---
- name: Create S3 bucket
  amazon.aws.s3_bucket:
    name: "{{ ocp4_workload_lb2739_s3_bucket_name }}"
    state: present
    access_key: "{{ aws_access_key_id }}"
    secret_key: "{{ aws_secret_access_key }}"
    region: "{{ aws_region }}"
    acl: "public-read-write"

- name: Save AgnosticD A3 Bucket data
  agnosticd_user_info:
    data:
      s3_bucket_name: "{{ ocp4_workload_lb2739_s3_bucket_name }}"
      s3_bucket_region: "{{ aws_region }}"
