---
- name: Set up S3 Bucket
  ansible.builtin.include_tasks: setup_s3_bucket.yml

- name: Set up second ROSA cluster
  ansible.builtin.include_tasks: setup_second_rosa_cluster.yml

- name: Deploy Kubevirt to second ROSA cluster
  ansible.builtin.include_tasks: setup_second_rosa_kubevirt.yml

- name: Set up FSxONTAP
  ansible.builtin.include_tasks: setup_fsxontap.yml

- name: Set up FSxONTAP post install configuration
  ansible.builtin.include_tasks: setup_fsxontap_post_config.yml
