---

# ----------------------------------------------------------------------
# Pre-destroy Workloads as role
# ----------------------------------------------------------------------
- name: Import Pre destroy workloads
  ansible.builtin.import_playbook: workloads.yml
  vars:
    _workload_title_: "Pre destroy"
    _workloads_: "{{ pre_destroy_workloads | default([]) }}"

- name: Import default destroy playbook
  ansible.builtin.import_playbook: ../../cloud_providers/{{cloud_provider}}_destroy_env.yml

# ----------------------------------------------------------------------
# Post-destroy Workloads as role
# ----------------------------------------------------------------------
- name: Import Post destroy workloads
  ansible.builtin.import_playbook: workloads.yml
  vars:
    _workload_title_: "Post Destroy"
    _workloads_: "{{ post_destroy_workloads | default([]) }}"