---

- name: Step 005 Post Software Started
  hosts: localhost
  gather_facts: false
  become: true
  tags:
    - step005
  tasks:
    - ansible.builtin.debug:
        msg: "Step 005 Post Software Started"

# ----------------------------------------------------------------------
# Post-Software Workloads as role
# ----------------------------------------------------------------------
- name: Import Post-software workloads
  ansible.builtin.import_playbook: workloads.yml
  vars:
     _workload_title_: "Post Software"
     _workloads_: "{{ post_software_workloads | default([]) }}"


- name: Deploy user setup
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - step005_02
    - post_software
  tasks:
    - name: For aws cloud provider
      when: cloud_provider == 'ec2'
      block:
        - name: print out user.info
          agnosticd_user_info:
            msg: |
              SSH Host: ssh {{ student_name }}@{{ groups['bastions'][0].split('.')[0] }}.{{ subdomain_base }}
              SSH Password: {{ student_password }}

        - name: Save user data
          agnosticd_user_info:
            data:
              ssh_command: "ssh {{ student_name }}@{{ groups['bastions'][0].split('.')[0] }}.{{ subdomain_base }}"
              ssh_password: "{{ student_password }}"
              ssh_username: "{{ student_name }}"
              cloud_provider: "{{ cloud_provider }}"
              targethost: "{{ groups['bastions'][0].split('.')[0] }}.{{ subdomain_base }}"
              hostname: "{{ groups['bastions'][0].split('.')[0] }}.{{ subdomain_base }}"
              subdomain_base: "{{ subdomain_base }}"
              subdomain_internal: "{{ aws_dns_zone_private_chomped | default('') }}"
          vars:
            student_name: "{{ ansible_service_account_user_name }}"
            bastion_prefix: "{{ groups['bastions'][0] | regex_replace('\\..*$') }}"
          register: r_user_data

    - name: For gcp cloud provider
      when: cloud_provider == 'gcp'
      block:
        - name: print out user.info
          agnosticd_user_info:
            msg: |
              SSH Host: ssh {{ student_name }}@bastion.{{ subdomain_base }}
              SSH Password: {{ student_password }}

        - name: Save user data
          agnosticd_user_info:
            data:
              ssh_command: "ssh {{ student_name }}@bastion.{{ subdomain_base }}"
              ssh_password: "{{ student_password }}"
              ssh_username: "{{ student_name }}"
              cloud_provider: "{{ cloud_provider }}"
              hostname: "bastion.{{ subdomain_base }}"
              subdomain_base: "{{ subdomain_base }}"

# ----------------------------------------------------------------------
# Final Post-Software Workloads as role
# ----------------------------------------------------------------------
- name: Import final Post-software workloads (Final Tasks of Deployment)
  ansible.builtin.import_playbook: workloads.yml
  vars:
    _workload_title_: "Post Software Final"
    _workloads_: "{{ post_software_final_workloads | default([]) }}"

- name: Step 005 Post Software Finished
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step005
  tasks:
    - ansible.builtin.debug:
        msg: "Step 005 Post Software Finished"
