---
- name: Step 003 Pre Software Started
  hosts: localhost
  gather_facts: false
  become: false
  tags:
    - step003
  tasks:
    - ansible.builtin.debug:
        msg: "Step 003 Pre Software Started"

# ----------------------------------------------------------------------
# Pre-Software Workloads as role
# ----------------------------------------------------------------------
- name: Import Pre-software workloads
  ansible.builtin.import_playbook: workloads.yml
  vars:
     _workload_title_: "Pre Software"
     _workloads_: "{{ pre_software_workloads | default([]) }}"


- name: Step 003 Pre Software Finished
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step003
  tasks:
    - ansible.builtin.debug:
        msg: "Step 003 Pre Software Finished"
