- name: Step 000 Pre Infrastructure Started
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step000
  tasks:
    - ansible.builtin.debug:
        msg: "Step 000 Pre Infrastructure Started"

# ----------------------------------------------------------------------
# Pre-infra Workloads as role
# ----------------------------------------------------------------------
- name: Import Post-infra workloads
  ansible.builtin.import_playbook: workloads.yml
  vars:
    _workload_title_: "Pre Infra"
    _workloads_: "{{ pre_infra_workloads | default([]) }}"


- name: Step 000 Pre Infrastructure Finished
  hosts: localhost
  gather_facts: false
  become: true
  tags:
    - step000
  tasks:
    - ansible.builtin.debug:
        msg: "Step 000 Pre Infrastructure Finished"
