collections:
  - name: ansible.posix
    version: 1.3.0
  - name: infra.controller_configuration
    version: 2.5.1
  - name: ansible.workshops
    version: 1.0.18
  - name: amazon.aws
    version: 3.1.1
  - name: google.cloud
    version: 1.3.0
  - name: https://github.com/rhpds/agd.gcp_infra.git
    type: git
    version: main
