---
- name: Step 004 Software Started
  hosts: localhost
  gather_facts: false
  become: false
  tags:
    - step004
  tasks:
    - ansible.builtin.debug:
        msg: "Step 004 Software Started"

# ----------------------------------------------------------------------
# Software Workloads as role
# ----------------------------------------------------------------------
- name: Import Software workloads
  ansible.builtin.import_playbook: workloads.yml
  vars:
     _workload_title_: "Software"
     _workloads_: "{{ software_workloads | default([]) }}"


- name: Step 004 Software Finished
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step004
  tasks:
    - ansible.builtin.debug:
        msg: "Step 004 Software Finished"
