---
controller_execution_environments:
  - name: "SAP Community Collection Executon Environment - latest"
    image: ghcr.io/sap-linuxlab/sap-ee:latest
  - name: "SAP Community Collection Execution Environment - stable"
    image: ghcr.io/sap-linuxlab/sap-ee:stable
  - name: "SAP Community Collection Execution Environment - dev"
    image: ghcr.io/sap-linuxlab/sap-ee:latest-dev
  - name: "SAP Supported Executon environment"  # needs secret to be usable
    image: quay.io/mkoch-redhat/sap-rh-ee:latest
