---
- name: Apply template {{ item }}
  become: true
  ansible.builtin.template:
    src: templates/{{ item.in_file }}
    dest: /home/{{student_name}}/{{ item.out_file }}
  loop:
    - in_file: deploy-app.sh.j2
      out_file: deploy-app.sh
    - in_file: validate-image.sh.j2
      out_file: validate-image.sh
    - in_file: create-vault-entries.sh.j2
      out_file: create-vault-entries.sh

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /home/{{student_name}}
    state: "{{ item.out_file }}"
    mode: a+x