---
- name: Apply template {{ item.in_file }}
  become: true
  ansible.builtin.template:
    src: templates/{{ item.in_file }}
    dest: /home/{{student_name}}/{{ item.out_file }}

- name: Change file ownership, group and permissions for {{ item.out_file }}
  ansible.builtin.file:
    path: /home/{{student_name}}/{{ item.out_file }}
    state: file
    mode: a+x