---
become_override: false
silent: false
ocp4_username: admin

ocp4_workload_rhdh_orchestrator_helm_installer: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
ocp4_workload_rhdh_orchestrator_helm_chart: https://github.com/rhdhorchestrator/orchestrator-helm-chart.git
ocp4_workload_rhdh_orchestrator_helm_chart_version: orchestrator-k8s-0.3.17
ocp4_workload_rhdh_orchestrator_sonataflow_pgsql_version: "12.12.10"

ocp4_workload_rhdh_orchestrator_sonataflow_namespace: sonataflow-infra
ocp4_workload_rhdh_orchestrator_serverless_enabled: true

ocp4_workload_rhdh_orchestrator_rhdh_name: developer-hub
ocp4_workload_rhdh_orchestrator_rhdh_namespace: tssc-dh

ocp4_workload_rhdh_orchestrator_workflows:
  repo: https://rhdhorchestrator.io/serverless-workflows-config
  chart:
  - name: greeting
    location: orchestrator-workflows/greeting