---
- name: Report user data
  throttle: 1
  agnosticd_user_info:
    data: >-
      {{
        {
          "hosts":
            lookup('agnosticd_user_data', 'hosts') |
            default({}, true) |
            combine({
              inventory_hostname: {
                "ssh_host": public_dns_name,
                "user": control_user_name,
                "password": control_user_password,
              }
            })
        }
        if control_user_enable_user_data_by_hostname | bool else
        {
          shortname ~ "_ssh_host": public_dns_name,
          shortname ~ "_user": control_user_name,
          shortname ~ "_password": control_user_password,
        }
        if control_user_enable_user_data_by_shortname | bool else
        {
          "ssh_host": public_dns_name,
          "user": control_user_name,
          "password": control_user_password,
        }
      }}

- name: Report user data ssh key
  when:
  - control_user_enable_user_data_ssh_provision_key | bool
  - hostvars.localhost.ssh_provision_key_path is defined
  agnosticd_user_info:
    data:
      ssh_private_key: "{{ lookup('file', hostvars.localhost.ssh_provision_key_path) }}"
...
