---
- name: Run host_workloads for destroy
  hosts: all:localhost
  gather_facts: false
  tasks:
  - name: Include host_workloads for destroy
    vars:
      agnosticd_stage: destroy
      host_workloads: "{{ destroy_workloads }}"
      host_workloads_become: "{{ destroy_workloads_become }}"
    ansible.builtin.include_role:
      name: host_workloads

- name: Import default cloud_provider destroy playbook
  ansible.builtin.import_playbook: ../../cloud_providers/{{ cloud_provider }}_destroy_env.yml
...
