---
- name: Step 006 Post Software
  hosts: localhost
  gather_facts: false
  become: true
  tags:
    - step006
    - post_software
  tasks:
    - ansible.builtin.debug:
        msg: "Post-Software tasks Started"

# ----------------------------------------------------------------------
# Post-Software Workloads as role
# ----------------------------------------------------------------------

- name: Run host_workloads for post_software_workloads
  hosts: all:localhost
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: Include host_workloads for post_software
      vars:
        agnosticd_stage: post_software
        host_workloads: "{{ post_software_workloads }}"
        host_workloads_become: "{{ post_software_workloads_become }}"
      ansible.builtin.include_role:
        name: host_workloads
...
