---

- name: Step 002 Post Infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - step002
    - post_infrastructure

  tasks:

    - name: "Step 002 Post Infrastructure"
      ansible.builtin.debug:
        msg: "Step 002 Post Infrastructure"
# ----------------------------------------------------------------------
# Post Infrasructure Workloads as role
# ----------------------------------------------------------------------

- name: Run host_workloads for post_infra_workloads
  hosts: all:localhost
  gather_facts: false
  tasks:
    - name: Include host_workloads for post_infra
      vars:
        agnosticd_stage: post_infra
        host_workloads: "{{ post_infra_workloads }}"
        host_workloads_become: "{{ post_infra_workloads_become }}"
      ansible.builtin.include_role:
        name: host_workloads
...
