---

- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step000
    - pre_infrastructure

  tasks:

    - name: "Step 000 Pre Infrastructure"
      ansible.builtin.debug:
        msg: "Step 000 Pre Infrastructure"

# ----------------------------------------------------------------------
# Pre-Infra Workloads as role
# ----------------------------------------------------------------------

- name: Run host_workloads for pre_infra_workloads
  hosts: all:localhost
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: Include host_workloads for pre_infra
      vars:
        agnosticd_stage: pre_infra
        host_workloads: "{{ pre_infra_workloads }}"
      ansible.builtin.include_role:
        name: host_workloads
...
