---
- name: Start Playbook
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Start Playbook
    ansible.builtin.debug:
      msg: "Start Playbook Running"

# ----------------------------------------------------------------------
# Start Workloads as role
# ----------------------------------------------------------------------

- name: Run host_workloads for start
  hosts: all:localhost
  gather_facts: false
  tasks:
  - name: Include host_workloads for start
    vars:
      agnosticd_stage: start
      host_workloads: "{{ start_workloads }}"
      host_workloads_become: "{{ start_workloads_become }}"
    ansible.builtin.include_role:
      name: host_workloads
...
