---
- name: Stop Playbook
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Stop Playbook
    ansible.builtin.debug:
      msg: "Stop Playbook Running"

# ----------------------------------------------------------------------
# Stop Workloads as role
# ----------------------------------------------------------------------

- name: Run host_workloads for stop
  hosts: all:localhost
  gather_facts: false
  tasks:
  - name: Include host_workloads for stop
    vars:
      agnosticd_stage: stop
      host_workloads: "{{ stop_workloads }}"
      host_workloads_become: "{{ stop_workloads_become }}"
    ansible.builtin.include_role:
      name: host_workloads
...
