---
# Implement your Workload deployment tasks here

- name: Install Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: rhods-operator
    install_operator_namespace: redhat-ods-operator
    install_operator_channel: "{{ ocp4_workload_openshift_ai_channel }}"
    install_operator_catalog: redhat-operators
    install_operator_automatic_install_plan_approval: "{{ ocp4_workload_openshift_ai_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ ocp4_workload_openshift_ai_starting_csv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_openshift_ai_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name: "{{ ocp4_workload_openshift_ai_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: redhat-ods-operator
    install_operator_catalogsource_image: "{{ ocp4_workload_openshift_ai_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_openshift_ai_catalog_snapshot_image_tag | default('') }}"

- name: Get installed CSVs
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: openshift-operators
  register: r_csvs

- name: Get cluster ingress config
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: r_ingress_config
  until: r_ingress_config.resources is defined
  retries: 10
  delay: 30

- name: Set ingress domain
  ansible.builtin.set_fact:
    _ocp4_workload_openshift_ai_ingress_domain: "{{ r_ingress_config.resources[0].spec.domain }}"

- name: Find CSV for the rhods operator
  set_fact:
    _ocp4_workload_openshift_ai_installed_operator_csv: "{{ item.metadata.name }}"
  loop: "{{ r_csvs.resources }}"
  when: "'rhods-operator' in item.metadata.name"

- name: Set Openshift AI Version 3 boolean
  ansible.builtin.set_fact:
    _ocp4_workload_openshift_ai_version_3: "{{ _ocp4_workload_openshift_ai_installed_operator_csv.startswith('rhods-operator.3.') }}"

- name: Create OpenShift AI Data Science Cluster
  when: _ocp4_workload_openshift_ai_version_3 | bool
  kubernetes.core.k8s:
    state: present
    template: redhat-datasciencecluster.yaml.j2
  register: r_ds_cluster
  until: not r_ds_cluster.failed
  retries: 10
  delay: 30

- name: Check if Data Science Cluster is ready
  kubernetes.core.k8s_info:
    api_version: datasciencecluster.opendatahub.io/{{ 'v2' if _ocp4_workload_openshift_ai_version_3 else 'v1' }}
    kind: DataScienceCluster
    name: default-dsc
  register: r_ds_cluster
  until:
  - r_ds_cluster.resources is defined
  - r_ds_cluster.resources | length > 0
  - r_ds_cluster.resources[0].status is defined
  - r_ds_cluster.resources[0].status.phase is defined
  - r_ds_cluster.resources[0].status.phase == 'Ready'
  retries: 60
  delay: 10

- name: Create OpenShift AI Dashboard Route
  when: _ocp4_workload_openshift_ai_version_3 | bool
  kubernetes.core.k8s:
    state: present
    template: rhods-dashboard-route.yaml.j2

- name: Get the OpenShift AI dashboard route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: rhods-dashboard
    namespace: redhat-ods-applications
  register: r_odh_dashboard_route
  until:
  - r_odh_dashboard_route.resources is defined
  - r_odh_dashboard_route.resources | length > 0
  - r_odh_dashboard_route.resources.0.status.ingress.0.host is defined
  - r_odh_dashboard_route.resources.0.status.ingress.0.host | length > 0
  retries: 80
  delay: 30

- name: Report OpenShift AI Dashboard URL
  agnosticd_user_info:
    msg: "RedHat OpenShift AI Dashboard: https://{{ r_odh_dashboard_route.resources[0].spec.host }}"
    data:
      rhodh_dashboard: "https://{{ r_odh_dashboard_route.resources[0].spec.host }}"
      rhoai_dashboard: "https://{{ r_odh_dashboard_route.resources[0].spec.host }}"

# Leave this as the last task in the playbook.
- name: Workload tasks complete
  when: not silent|bool
  ansible.builtin.debug:
    msg: "Workload Tasks completed successfully."
