---
- name: Login with azure admin user
  when: env_type == 'open-environment-azure'
  ansible.builtin.command: >-
    az login
    -u "{{ azure_user }}"
    -p "{{ azure_user_password }}"
    --tenant "{{ azure_tenant }}"
  no_log: true

- name: Login with azure admin service principal
  when: env_type == 'open-environment-azure-subscription'
  ansible.builtin.command: >-
    az login --service-principal
    -u "{{ azure_service_principal }}"
    -p "{{ azure_password }}"
    --tenant "{{ azure_tenant }}"
  no_log: true

## This app_id is constant for all azure tenants
#- name: Get Azure Red Hat OpenShift RP SP info
#  azure.azcollection.azure_rm_adserviceprincipal_info:
#    auth_source: cli
#    app_id: "{{ open_env_azure_aro_ai_search_federated_app_id }}"
#    tenant: "{{ azure_tenant }}"
#  register: azrpsp
#
- name: Set default subscription
  when: env_type == 'open-environment-azure-subscription'
  ansible.builtin.command: >-
    az account set
    --subscription {{ azure_subscription }}
