---
- name: Login to Azure services
  ansible.builtin.include_tasks:
    file: ./login-to-cluster.yml

- name: Setup Azure AI Search
  ansible.builtin.include_tasks:
    file: ./aro-ai-search-federated.yml
