---

- name: Create group {{ zero_touch_rhel_user_user_group }}
  ansible.builtin.group:
    name: "{{ zero_touch_rhel_user_user_group }}"
    state: present

- name: Create user {{ zero_touch_rhel_user_user_name }}
  ansible.builtin.user:
    name: "{{ zero_touch_rhel_user_user_name }}"
    group: "{{ zero_touch_rhel_user_user_group }}"
    password: "{{ zero_touch_rhel_user_user_password | password_hash('sha512') }}"
    state: present

- name: Enable sudoers
  when: zero_touch_rhel_user_enable_sudoers | default(false) | bool
  ansible.builtin.copy:
    content: >-
      {{ zero_touch_rhel_user_user_name }}
      ALL=(ALL) {{ zero_touch_rhel_user_sudo_commands | default('NOPASSWD: ALL') }}
    dest: '/etc/sudoers.d/{{ zero_touch_rhel_user_user_name }}'
    mode: u=rw,g=r,o=r

- name: Enable Password Authentication (TODO)
  block:
    - name: Enable password authentication
      ansible.builtin.lineinfile:
        line: PasswordAuthentication yes
        regexp: '^ *PasswordAuthentication'
        path: /etc/ssh/sshd_config

    - name: Remove PasswordAuthentication line from 50-cloud-init.conf
      when: bastion_remove_cloud_init_conf | default(true) | bool
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        regexp: PasswordAuthentication
        state: absent

    - name: Disable root password authentication
      ansible.builtin.lineinfile:
        line: PermitRootLogin without-password
        regexp: '^ *PermitRootLogin'
        path: /etc/ssh/sshd_config

    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
