---
- name: Check for required variables
  ansible.builtin.assert:
    that:
      - ocp4_workload_rhoso_ipam4lab_service_url
      - ocp4_workload_rhoso_ipam4lab_allocation_name
      - ocp4_workload_rhoso_ipam4lab_cluster_name
    quiet: true
    fail_msg: >
      Required variables not defined: ocp4_workload_rhoso_ipam4lab_service_url,
      ocp4_workload_rhoso_ipam4lab_allocation_name, and
      ocp4_workload_rhoso_ipam4lab_cluster_name must be set

- name: Pre-workload tasks complete
  when: not silent | bool
  ansible.builtin.debug:
    msg: "Pre-Workload tasks completed successfully."
