- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step001
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure"

# ----------------------------------------------------------------------
# Pre-infra Workloads as role
# ----------------------------------------------------------------------
- name: Import Post-infra workloads
  import_playbook: workloads.yml
  vars:
    _workload_title_: "Pre Infra"
    _workloads_: "{{ pre_infra_workloads | default([]) }}"
