---
ocp4_workload_lb2739_first_rosa_cidr: ""

ocp4_workload_lb2739_second_rosa_name: "dr-{{ guid }}"
ocp4_workload_lb2739_second_rosa_cidr: "10.10.0.0/16"
ocp4_workload_lb2739_second_rosa_compute_replicas: 2
ocp4_workload_lb2739_second_rosa_version: "4.16.37"

ocp4_workload_lb2739_second_rosa_binary_path: "/usr/local/bin"
ocp4_workload_lb2739_second_rosa_installer_version: latest
ocp4_workload_lb2739_second_rosa_installer_url: >-
  https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/rosa/{{ rosa_installer_version }}/rosa-linux.tar.gz

ocp4_workload_lb2739_fsx_name1: PROD-FSXONTAP
ocp4_workload_lb2739_fsx_name2: DR-FSXONTAP

ocp4_workload_lb2739_policy_name1: ProdTridentIAMPolicy
ocp4_workload_lb2739_policy_name2: DRTridentIAMPolicy

ocp4_workload_lb2739_fsx_admin_password: ""
ocp4_workload_lb2739_svm_admin_password: ""
