---
- name: Build inventory
  ansible.builtin.import_playbook: post_infra.yml

- name: Start or stop workload(s)
  hosts: ocp_bastions
  become: false
  gather_facts: false
  tags:
    - step005
  tasks:
  - name: Fail if no action defined
    when: ACTION is not defined or ACTION == ''
    ansible.builtin.fail:
      msg: ACTION must be defined

  - name: Run Workloads to perform {{ ACTION }}
    loop: "{{ cluster_workloads }}"
    loop_control:
      loop_var: __workload
      label: "{{ __workload.name }}"
    include_tasks: run_workload_on_clusters.yml
    vars:
      ACTION: destroy # placeholder, ACTION will be start or stop

- name: Cleanup
  ansible.builtin.import_playbook: cleanup.yml
