---
become_override: true
ocp_username: opentlc-mgr
silent: false

repo_user: RHsyseng
lab_repo: "https://github.com/{{ repo_user }}/hypershift-baremetal-lab.git"
lab_version: "lab-4.18"
lab_release: "4.18"
ocp4_major_release: "4.18"
lab_network_cidr: "192.168.125.0/24"
lab_network_domain: "hypershift.lab"
lab_registry_host: "infra.{{ lab_network_domain }}:8443"
lab_api_host: "api.management.{{ lab_network_domain }}:6443"
# yamllint disable rule:line-length
kcli_rpm_url: "https://github.com/{{ repo_user }}/hypershift-baremetal-lab/releases/download/4.18/kcli-99.0.0.git.202504110956.affb930-0.el9.x86_64.rpm"
# yamllint enable rule:line-length
epel_release: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
upstream_dns: "1.1.1.1"
lab_mgmt_vm_cpus: 16
lab_mgmt_vm_memory: 48000
lab_mgmt_vm_disk: 200
lab_hosted_vm_cpus: 12
lab_hosted_vm_memory: 24000
lab_hosted_vm_disk: 200
extra_disk_libvirt_images: true