---
- name: Install Helm as root
  become: true
  block:

  - name: Install Helm as root
    become: true
    block:
    - name: Install helm command
      ansible.builtin.unarchive:
        src: "{{ helm_url }}"
        remote_src: true
        dest: /usr/local/bin
        mode: "0775"
        owner: root
        group: root
      retries: 10
      register: r_client
      until: r_client is success
      delay: 30

    - name: Link downloaded helm command to helm
      ansible.builtin.file:
        src: /usr/local/bin/linux-amd64/helm
        dest: /usr/local/bin/helm
        owner: root
        group: root
        state: link

    - name: Create Helm Bash completion file
      ansible.builtin.shell: /usr/local/bin/helm completion bash >/etc/bash_completion.d/helm
