---
- name: Setup Red Hat packages for bastion
  when: bastion_install_basic_packages | bool
  ansible.builtin.package:
    state: present
    name: "{{ agd_bastion_packages }}"
  register: r_dnf_packages
  until: r_dnf_packages is succeeded
  retries: "{{ bastion_install_basic_packages_retries | default(5) }}"
  delay: 10
  tags:
    - install_bastion_packages

- name: Setup ssh config customization
  block:

    - name: Generate host .ssh/config Template
      ansible.builtin.template:
        src: "{{ role_path }}/templates/bastion_ssh_config.j2"
        dest: "{{ output_dir }}/ssh-config-{{ env_type }}-{{ guid }}"
      delegate_to: localhost
      become: false
      tags:
        - gen_sshconfig_file

    - name: copy over host .ssh/config Template
      ansible.builtin.copy:
        src: "{{ output_dir }}/ssh-config-{{ env_type }}-{{ guid }}"
        dest: /root/.ssh/config
        owner: root
        group: root
        mode: 0400
      become: true
      tags:
        - copy_sshconfig_file

- name: Add GUID to ~{{ ansible_user }}/.bashrc
  ansible.builtin.lineinfile:
    path: "~{{ ansible_user }}/.bashrc"
    regexp: "^export GUID"
    line: "export GUID={{ guid }}"
    create: true

- name: Write external IP to user home directory (CNV)
  when:
    - cloud_provider == "openshift_cnv"
    - hostvars[inventory_hostname]['external_ip'] is defined
    - hostvars[inventory_hostname]['external_ip'] != ""
  ansible.builtin.copy:
    content: "{{ hostvars[inventory_hostname]['external_ip'] }}"
    dest: "~{{ ansible_user }}/external_ip"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

  # TODO: Is there any value in doing the below?
  #       Discuss with team and consider "per cloud" includes
  #       Leave for now as a reminder and reference
  # block:

  #   - name: Add GUID to /etc/skel/.bashrc
  #     ansible.builtin.lineinfile:
  #       path: /etc/skel/.bashrc
  #       regexp: "^export GUID"
  #       line: "export GUID={{ guid }}"

    # TODO: Make this conditional on being OSP
    # validate first it's not being used elsewhere

    # - name: Add CLOUDUSER to /etc/skel/.bashrc
    #   ansible.builtin.lineinfile:
    #     path: /etc/skel/.bashrc
    #     regexp: "^export CLOUDUSER"
    #     line: "export CLOUDUSER={{ ansible_user }}"

    # - name: Add CLOUDUSER to ~{{ ansible_user }}/.bashrc
    #   ansible.builtin.lineinfile:
    #     path: "~{{ ansible_user }}/.bashrc"
    #     regexp: "^export CLOUDUSER"
    #     line: "export CLOUDUSER={{ ansible_user }}"

...
