---
- name: Delete SSH Public Key pair using ibmcloud CLI
  command: >-
    ibmcloud is key-delete {{ ibmcloud_resource_group_name }}-ssh-key
    --force
  register: r_ibmcloud_delete_ssh_public_key
  until: r_ibmcloud_delete_ssh_public_key is succeeded
  retries: 5
  failed_when: >-
    r_ibmcloud_delete_ssh_public_key.rc != 0
    and 'not found' not in r_ibmcloud_delete_ssh_public_key.stderr
  changed_when: >-
    r_ibmcloud_delete_ssh_public_key.rc == 0
