---
- name: Delete IBM Cloud Virtual Server (VS) instance
  register: ibmcloud_vs_instance_create
  ibm.cloudcollection.ibm_is_instance:
    region: "{{ ibmcloud_region }}"
    state: absent
    id: "{{ instance.id }}"
    image: "{{ instance.image }}"
    vpc: "{{ instance.vpc }}"
    zone: "{{ instance.zone }}"
    profile: "{{ instance.profile }}"
    primary_network_interface:
      - name: "{{ instance.primary_network_interface[0].name }}"
        subnet: "{{ instance.primary_network_interface[0].subnet }}"
    keys: "{{ instance.keys }}"
    resource_group: "{{ r_ibmcloud_resource_group_id }}"
