---
- name: Login (ibmcloud CLI)
  command: >-
    ibmcloud login --quiet
    --apikey {{ ibmcloud_api_key |quote }}
    -r {{ ibmcloud_region | quote }}
    -g {{ ibmcloud_resource_group_name | quote }}

- name: Disable auto update checks
  command: >-
      ibmcloud config --check-version=false
