---
- name: Login (ibmcloud CLI)
  command: >-
    ibmcloud login --quiet
    --apikey {{ ibmcloud_api_key |quote }}
    -r {{ ibmcloud_region | quote }}
    -g {{ ibmcloud_resource_group_name | quote }}
  retries: 5
  delay: 60
  register: ibmcloud_login
  until: ibmcloud_login is succeeded

- name: Disable auto update checks
  command: >-
      ibmcloud config --check-version=false
