---
- name: Set up users permissions to see node network configuration and allow NaD creation
  when: ocp4_workload_virt_network_config_multi_user | default(false)
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', resource | from_yaml) }}"
  register: r_cluster_roles
  until: r_cluster_roles is success
  retries: 20
  delay: 10
  loop:
  - clusterrole-list-nodenetworkstates.yaml
  - clusterrolebinding-list-nodenetworkstates.yaml
  - clusterrole-list-nodenetworkconfigurationresources.yaml
  - clusterrolebinding-list-nodenetworkconfigurationresources.yaml
  - clusterrole-network-attachment-admin.yaml
  - clusterrolebiding-network-attachment-admin.yaml
  loop_control:
    loop_var: resource

- name: Create NNCP (linux-bridge)
  when:
  - ocp4_workload_virt_network_config_networks | default([]) | length > 0
  - ocp4_workload_virt_network_config_bridge_type == "linux-bridge"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'nodenetworkconfigurationpolicy-linux-bridge.yaml.j2') | from_yaml }}"
  register: r_nncp_linux_bridge
  until: r_nncp_linux_bridge is success
  retries: 20
  delay: 10

- name: Create NNCP (ovs-bridge)
  when:
  - ocp4_workload_virt_network_config_networks | default([]) | length > 0
  - ocp4_workload_virt_network_config_bridge_type == "ovs-bridge"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'nodenetworkconfigurationpolicy-ovs-bridge.yaml.j2') | from_yaml }}"
  register: r_nncp_ovs_bridge
  until: r_nncp_ovs_bridge is success
  retries: 20
  delay: 10
